import React from "react";
import { Stack, Heading, Text, Button } from "@chakra-ui/react";
import FeatureCard from "@/cards/FeatureCard";

const Features = () => {
  return (
    <div className="mainContainer" id="features">
      <Stack
        align={"center"}
        spacing={{ base: 8, md: 30 }}
        pt={{ base: 20, md: 20 }}
        direction={{ base: "column", md: "row" }}
        textAlign={{ base: "center", md: "left" }}
      >
        <Heading variant="primary-heading">Our Features you can get</Heading>
        <Text color={"gray.500"} variant="secondary-text">
          Gain in-depth analytics for your dev.to blog and receive personalized
          topic ideas generated by AI, based on your previous articles.
        </Text>
        {/* <Button variant="capsule-button" backgroundColor="#8B54BD">
          <Text className="primary-text">Try it now</Text>
        </Button> */}
      </Stack>
      <Stack
        spacing={{ base: 8, md: 10 }}
        pb={{ base: 15, md: 20 }}
        mt={{ base: 7, md: 10 }}
        direction={{ base: "column", md: "row" }}
      >
        {FeaturesCardData &&
          FeaturesCardData.map((item, index) => {
            return (
              <FeatureCard
                index={item.index}
                title={item.title}
                desc={item.desc}
                key={index}
              />
            );
          })}
      </Stack>
    </div>
  );
};

const FeaturesCardData = [
  {
    index: 0,
    title: "Topic Generation",
    desc: "Generate topic ideas based on previous articles performance on the platform.",
  },
  {
    index: 1,
    title: "Scheduling Article",
    desc: "Helping you writing, scheduling and publish article across mulitple platform from one place.",
  },
  {
    index: 2,
    title: "Realtime Analytics",
    desc: "We provide you analytics of your blog with more metrics.",
  },
];

export default Features;
