import {
  Stack,
  Flex,
  Box,
  Heading,
  Text,
  Button,
  Center,
  SimpleGrid,
} from "@chakra-ui/react";
import { AiOutlinePlayCircle } from "react-icons/ai";
import { SiNotion, SiUnsplash, SiGrammarly, SiOpenai } from "react-icons/si";
import { IconContext } from "react-icons/lib";
import Image from "next/image";
import HeroImg from "@/public/images/Hero.png";

export default function Hero() {
  return (
    <Box className="mainContainer">
      <Stack
        align={"center"}
        spacing={{ base: 8, md: 10 }}
        py={{ base: 20, md: 28 }}
        direction={{ base: "column", md: "row" }}
      >
        <Stack flex={1} spacing={{ base: 5, md: 10 }}>
          <Heading variant="hero-heading">
            Powered your technical writing with AI
          </Heading>
          <Text color={"gray.500"} variant="secondary-text">
            Gain in-depth analytics for your dev.to blog and receive
            personalized topic ideas generated by AI, based on your previous
            articles.
          </Text>
          <Stack
            spacing={{ base: 4, sm: 6 }}
            direction={{ base: "column", sm: "row" }}
          >
            <Button variant="capsule-button" backgroundColor="#8B54BD">
              <Text className="primary-text">Try it now</Text>
            </Button>
            <Button variant="capsule-button">
              <IconContext.Provider value={{ color: "black", size: "2em" }}>
                <AiOutlinePlayCircle />
              </IconContext.Provider>
              <Text className="primary-text" color="black" pl={2}>
                See how it works
              </Text>
            </Button>
          </Stack>
        </Stack>
        <Flex
          flex={1}
          justify={"center"}
          align={"center"}
          position={"relative"}
          w={"full"}
        >
          <Image alt="Hero Image" src={HeroImg} width={300} height={300} />
        </Flex>
      </Stack>
      <Box>
        <Center>
          <Heading variant="bold-medium-heading">
            More than 25,000 teams use Collabs
          </Heading>
        </Center>
        <Center>
          <SimpleGrid columns={[2, 2, 4]} spacing={20} mt={10}>
            <Flex alignItems="center">
              <IconContext.Provider value={{ color: "#A6A6A6", size: "2em" }}>
                <SiNotion />
                <Heading variant="secondary-heading" color="#A6A6A6">
                  Notion
                </Heading>
              </IconContext.Provider>
            </Flex>
            <Flex alignItems="center">
              <IconContext.Provider value={{ color: "#A6A6A6", size: "2em" }}>
                <SiOpenai />
                <Heading variant="secondary-heading" color="#A6A6A6">
                  OpenAI
                </Heading>
              </IconContext.Provider>
            </Flex>
            <Flex alignItems="center">
              <IconContext.Provider value={{ color: "#A6A6A6", size: "2em" }}>
                <SiGrammarly />
                <Heading variant="secondary-heading" color="#A6A6A6">
                  grammarly
                </Heading>
              </IconContext.Provider>
            </Flex>
            <Flex alignItems="center">
              <IconContext.Provider value={{ color: "#A6A6A6", size: "2em" }}>
                <SiUnsplash />
                <Heading variant="secondary-heading" color="#A6A6A6">
                  Unsplash
                </Heading>
              </IconContext.Provider>
            </Flex>
          </SimpleGrid>
        </Center>
      </Box>
    </Box>
  );
}
